"""Add ISBN Column

Revision ID: de68fb8660fd
Revises: 5c9abcf3c081
Create Date: 2024-11-30 20:06:26.894622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de68fb8660fd'
down_revision: Union[str, None] = '5c9abcf3c081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
